language: c

# use container infra for linux
sudo: false

addons:
  apt:
    packages:
      - php5-cli
      - python2.7
      - python3.4
#      - ruby
#      - rubygems
#      - valgrind

os:
  - osx
  - linux

branches:
  only:
    - master

# try some different compilers
compiler:
  - gcc
#  - clang

# for the ruby-watchman gem
#gemfile: ruby/ruby-watchman/Gemfile
#rvm:
#  - "2.0.0"

# try some different compiler options
env:
  - CONFIGARGS=""
#  - CONFIGARGS="--enable-stack-protector"
#  - CONFIGARGS="" WATCHMAN_VALGRIND=1

before_script: ./travis/deps.sh
script: ./travis/run.sh
