language: c

# use container infra for linux
dist: trusty
sudo: false

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - php5-cli
      - python2.7
      - python2.7-dev
      - python3.5
      - python3.5-dev
      - python3.6
      - python3.6-dev
      - gcc-4.8
      - g++-4.8
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
#      - ruby
#      - rubygems
#      - valgrind

branches:
  only:
    - master

# for the ruby-watchman gem
#gemfile: ruby/ruby-watchman/Gemfile
#rvm:
#  - "2.0.0"

# TODO: On Linux we currently use system versions of Python. That makes it
# somewhat annoying to get third-party dependencies in, since sudo isn't
# available. We should figure out how to solve this for real, either with
# virtualenv or with the pyenv mechanism Hypothesis uses:
# http://www.drmaciver.com/2015/10/a-whirlwind-tour-of-the-hypothesis-build/
matrix:
  include:
    - os: osx
      env: TRAVIS_PYTHON=python2.6
    - os: osx
      env: TRAVIS_PYTHON=python2.7
    - os: osx
      env: TRAVIS_PYTHON=python3.5
    - os: osx
      env: TRAVIS_PYTHON=python3.6
    - os: osx
      osx_image: xcode7.3
      env: TRAVIS_PYTHON=python2.7 ENABLE_ASAN=1
    - os: osx
      osx_image: xcode7.3
      env: TRAVIS_PYTHON=python3.5 ENABLE_ASAN=1
    - os: osx
      osx_image: xcode8.3
      env: TRAVIS_PYTHON=python3.6 ENABLE_ASAN=1
    - os: linux
      env: TRAVIS_PYTHON=python2.7 ENABLE_ASAN=1 CXX=g++-5
      compiler: gcc-5
    - os: linux
      env: TRAVIS_PYTHON=python3.5 ENABLE_ASAN=1 CXX=g++-5
      compiler: gcc-5
    - os: linux
      env: TRAVIS_PYTHON=python3.6 ENABLE_ASAN=1 CXX=g++-6
      compiler: gcc-6
    - os: linux
      env: TRAVIS_PYTHON=python2.7 CXX=g++-4.8
      compiler: gcc-4.8
    - os: linux
      env: TRAVIS_PYTHON=python3.5 CXX=g++-4.8
      compiler: gcc-4.8
    - os: linux
      env: TRAVIS_PYTHON=python3.6 CXX=g++-4.8
      compiler: gcc-4.8

before_script: ./travis/deps.sh
script: ./travis/run.sh
