[package]
name = "serde_bser"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>"]

[dependencies]
byteorder = "1.0"
bytes = "0.4"
error-chain = "*"
serde = "1"
serde_bytes = "0.11"
serde_derive = "1"

[features]
default = []
debug_bytes = []

[dev-dependencies]
maplit = "1.0"
